-- MySQL Script generated by MySQL Workbench
-- Mon Jan  4 18:18:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gift_certificates
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gift_certificates
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gift_certificates` DEFAULT CHARACTER SET utf8 ;
USE `gift_certificates` ;

-- -----------------------------------------------------
-- Table `gift_certificates`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gift_certificates`.`tag` ;

CREATE TABLE IF NOT EXISTS `gift_certificates`.`tag` (
  `id_tag` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_certificates`.`gift_certificate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gift_certificates`.`gift_certificate` ;

CREATE TABLE IF NOT EXISTS `gift_certificates`.`gift_certificate` (
  `ig_gift_certificate` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `price` DECIMAL NOT NULL,
  `duration` INT NOT NULL,
  `create_date` TIMESTAMP NOT NULL,
  `last_update_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ig_gift_certificate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_certificates`.`gift_certificate_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gift_certificates`.`gift_certificate_tag` ;

CREATE TABLE IF NOT EXISTS `gift_certificates`.`gift_certificate_tag` (
  `gift_certificate_ig_gift_certificate` INT NOT NULL,
  `tag_id_tag` INT NOT NULL,
  PRIMARY KEY (`gift_certificate_ig_gift_certificate`, `tag_id_tag`),
  INDEX `fk_gift_certificate_has_tag_tag1_idx` (`tag_id_tag` ASC),
  INDEX `fk_gift_certificate_has_tag_gift_certificate_idx` (`gift_certificate_ig_gift_certificate` ASC),
  CONSTRAINT `fk_gift_certificate_has_tag_gift_certificate`
    FOREIGN KEY (`gift_certificate_ig_gift_certificate`)
    REFERENCES `gift_certificates`.`gift_certificate` (`ig_gift_certificate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gift_certificate_has_tag_tag1`
    FOREIGN KEY (`tag_id_tag`)
    REFERENCES `gift_certificates`.`tag` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
