-- MySQL Script generated by MySQL Workbench
-- Wed Jan 13 23:16:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gift_certificates
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gift_certificates
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gift_certificates` DEFAULT CHARACTER SET utf8 ;
USE `gift_certificates` ;

-- -----------------------------------------------------
-- Table `gift_certificates`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_certificates`.`tag` (
  `id_tag` INT NOT NULL AUTO_INCREMENT,
  `name_tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tag`),
  UNIQUE INDEX `name_UNIQUE` (`name_tag` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_certificates`.`gift_certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_certificates`.`gift_certificate` (
  `id_gift_certificate` INT NOT NULL AUTO_INCREMENT,
  `name_gift_certificate` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `price` DECIMAL NOT NULL,
  `duration` INT NOT NULL,
  `create_date` TIMESTAMP NOT NULL,
  `last_update_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_gift_certificate`),
  UNIQUE INDEX `name_UNIQUE` (`name_gift_certificate` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_certificates`.`gift_certificate_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_certificates`.`gift_certificate_tag` (
  `id_gift_certificate` INT NOT NULL,
  `id_tag` INT NOT NULL,
  PRIMARY KEY (`id_gift_certificate`, `id_tag`),
  INDEX `fk_gift_certificate_has_tag_tag1_idx` (`id_tag` ASC),
  INDEX `fk_gift_certificate_has_tag_gift_certificate_idx` (`id_gift_certificate` ASC),
  CONSTRAINT `fk_gift_certificate_has_tag_gift_certificate`
    FOREIGN KEY (`id_gift_certificate`)
    REFERENCES `gift_certificates`.`gift_certificate` (`id_gift_certificate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gift_certificate_has_tag_tag1`
    FOREIGN KEY (`id_tag`)
    REFERENCES `gift_certificates`.`tag` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
